import { Inter } from "next/font/google"; // Correct import for Inter font
import "./globals.css";
import Navbar from "./component/navbar";
import Footer from "./component/footer";

// Define metadata without using Metadata type explicitly
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer/>
        {/* <Footer/> */}
      </body>
    </html>
  );
}


